on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Setup zig"
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - name: "Run tests"
        run: |
          ls -l
          tree -l
          zig test src/*/*.zig
